language:
  - cpp

sudo: true

cache:
  directories:
    - linux_dependencies
    - osx_dependencies

matrix:
  include:
    - stage: "Code Style"
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-format-6.0
      script:
        - |
            if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then
                # for pull requests check changes from last full branch till master
                git --no-pager clang-format-6.0 master --diff
            else
                # for non-pull requests check only last commit changes
                git --no-pager clang-format-6.0 HEAD~1 --diff
            fi
        - travis_terminate 0

    - stage: "Supported Compilers"
      os: osx
      osx_image: xcode9.3

    - os: linux
      env: >
      compiler: gcc
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - libboost1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-iostreams1.55-dev
            - libboost-program-options1.55-dev
            - libboost-regex1.55-dev
            - libboost-log1.55-dev
            - ninja-build


script:
  - |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
        echo "installing dependencies for linux"
        ./install_dependencies.sh
    fi
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
        echo "installing dependencies for osx"
        ./install_dependencies.sh osx
    fi
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - cd ..
  - ls build/bin
  - ./build/bin/srb_decompressor < test/compressed_files/hello.cpp.gz
  - ./build/bin/srb_decompressor < test/compressed_files/hello.cpp.bz2
